kind: pipeline
name: default

steps:
  - name: Test with perl 5.28
    image: perl:5.28
    commands:
      - cpanm -q --notest --installdeps .
      - plackup ./feedro.pl --listen 'localhost:3000' &
      - yath --qvf
